### ISSUE TITLE
batchDemux into MKVs?

### ISSUE THREAD

**Issue by IngwiePhoenix** [ToaHartor/GI-cutscenes#23]
So I just batchDemux'd all the cutscenes in prep of rewatching them with friends. But, how do I turn the huge amount of files in my output folder into MKVs as described in the readme?

Thanks :)

**Comment by ToaHartor** [comment]
Did you end up with a lot of hca, wav and ivf files in the output folder ?

**Comment by IngwiePhoenix** [comment]
Yep!

I also noticed that `appsettings.json` didn't have the paths for FFmpeg and mkvtools in it, so I added them manually (and properly escaping backslashes):

```json
{
  "Settings": {
    "MkvMergePath": "C:\\Program Files\\MKVToolNix\\mkvmerge.exe",
    "FfmpegPath": "C:\\ProgramData\\chocolatey\\bin\\ffmpeg.exe",
    "SubsFolder": "./GenshinData/Subtitle"
  }
}
```

Invocation was: `./GICutscenes.exe batchDemux "...path to genshin..." -o out`

Anything I missed?

**Comment by IngwiePhoenix** [comment]
Full command: `.\GICutscenes.exe batchDemux "C:\tools\Genshin Impact\Genshin Impact game\GenshinImpact_Data\StreamingAssets\VideoAssets\StandaloneWindows64" -o out`

**Comment by ToaHartor** [comment]
You're missing a few options in your command line. If you want to merge everything with the subtitles, you can try `./GICutscenes.exe batchDemux "...path to genshin..." -o out -m -s` (`-m` to merge the files and `-s` to add the subtitles) 
You might want to add as well the `--engine` option followed by either `internal`, `ffmpeg` or `mkvmerge`, if you don't then it will simply use its own merging system (internal)

Also, in order to merge the subtitles, you must have the subtitles folder at the path "SubsFolder", and the fonts in the same folder than the program.

**Comment by Unknow-404** [comment]
> Yep!
> 
> I also noticed that `appsettings.json` didn't have the paths for FFmpeg and mkvtools in it, so I added them manually (and properly escaping backslashes):
> 
> ```json
> {
>   "Settings": {
>     "MkvMergePath": "C:\\Program Files\\MKVToolNix\\mkvmerge.exe",
>     "FfmpegPath": "C:\\ProgramData\\chocolatey\\bin\\ffmpeg.exe",
>     "SubsFolder": "./GenshinData/Subtitle"
>   }
> }
> ```
> 
> Invocation was: `./GICutscenes.exe batchDemux "...path to genshin..." -o out`
> 
> Anything I missed?

You should use this option to merge the mkv --merge

**Comment by IngwiePhoenix** [comment]
I see; those were not documented in the help screen on the tool. Thanks for the info, I'll try that now then!
