### ISSUE TITLE
plz update versions.json to 2.8

### ISSUE THREAD

**Issue by MLChinoo** [ToaHartor/GI-cutscenes#26]
plz update versions.json to 2.8

**Comment by ToaHartor** [comment]
It's in the works. The thing is that the way we use to obtain those keys requires traffic dumping (as of 2.7, you can see #8). However, since version 2.8 it requires an additional process to be able to decrypt the traffic. Therefore we currently can't get those keys.
I hope it'll be possible but I can't guarantee it.

**Comment by ToaHartor** [comment]
You may be interested to check the associated pull request #27 👀, will close this once merged.
