### ISSUE TITLE
I found that the latest game version missing some old .usm files....

### ISSUE THREAD

**Issue by Liujunhua007** [ToaHartor/GI-cutscenes#49]
求一份备份，收集下老cg

Get a backup and collect the old cg

**Comment by ToaHartor** [comment]
The ones that comes to my mind are the two cutscenes from the 1.1 event of Fischl and Mona. Otherwise, I'm not aware of the deletion of some cutscenes from the entire package, but I wouldn't be surprised if they started doing that to save storage space, like for the mobile version.

Anyway, past versions links can be found in [this repository](https://github.com/kyou-nase/GI-Download-Library) (and individual files can be directly retrieved with the ScatteredFiles path)

**Comment by Liujunhua007** [comment]
ok,thanks
