### ISSUE TITLE
Change resolution and FPS, and the Key

### ISSUE THREAD

**Issue by JRSKelvin** [ToaHartor/GI-cutscenes#73]
First, thank you so much (all developers and contributors) for the GI Cutscenes tool you have developed. It's nice and perfect work. But may I give some opinions and questions from myself, which the first is may you add more features that can change resolution and frame per second in the video file? I have tried and checked that resolutions are 1080p and 30fps, I think maybe able to export to 4k? (I'm sorry due I'm still new to Unity and Game Engine). Then may I know how to get that key to export the USM file? I'm curious and searched on the internet, but found nothing. Once again, thank you and I'll wait for your reply.

Best Regards,
JRSKelvin

**Comment by Unknow-404** [comment]
Only 1080P 30fps videos are included in the USM source files.

**Comment by Unknow-404** [comment]
About the key, you can view it on: [8#](https://github.com/ToaHartor/GI-cutscenes/issues/8#issuecomment-1146618993) or [27#](https://github.com/ToaHartor/GI-cutscenes/pull/27#issue-1308663377).

**Comment by JRSKelvin** [comment]
Ok, thank you for your answers and information @Unknow-404. I'll continue to follow up on this repository and learn about Unity Game Engine.

**Comment by ToaHartor** [comment]
About the video options, I guess it would be possible to upscale it or to have a higher framerate since we can use ffmpeg to do that. But in the end, it would only make the output file bigger without any significant changes in my opinion, since it will re-encode it. I guess it's up to the users to see if it's useful or not.

As an additional knowledge, USM is a proprietary format used to contain video and audio tracks (like mkv files), but allowing the content to be encrypted, looped, and streamed in CriWare's proprietary player. It doesn't have anything to do with Unity in itself, since it's only using an external library in the game.

**Comment by JRSKelvin** [comment]
Thank you @ToaHartor for your reply and additional knowledge. I'm a GI player and curious about what is inside GI_data, so I searched online and found several discussions and repositories, including this. I'll keep continuing to learn and search on the Internet. I also will follow up for future updates on this development. Possibly I can contribute if have any updates or development that I have.
